version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.9.0
    - 3.9.1
  - dependency-name: firebase
    versions:
    - 8.2.10
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.9
    - 8.3.0
    - 8.3.1
    - 8.3.2
    - 8.4.0
  - dependency-name: vuetify
    versions:
    - 2.4.4
    - 2.4.5
    - 2.4.6
    - 2.4.7
    - 2.4.8
    - 2.4.9
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: vue-cli-plugin-vuetify
    versions:
    - 2.1.0
    - 2.2.0
    - 2.2.2
    - 2.3.1
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: sass
    versions:
    - 1.32.7
    - 1.32.8
  - dependency-name: vuetify-loader
    versions:
    - 1.7.1
  - dependency-name: vue-router
    versions:
    - 3.5.1
